%YAML 1.2
---
# Snapcraft Recipe for Epson GT-S650 Scanner Plugin Content Snap for Utsushi Snap
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * Snapcraft.yaml reference
#   https://forum.snapcraft.io/t/snapcraft-yaml-reference/4276
# * The snapcraft syntax
#   https://docs.snapcraft.io/build-snaps/syntax
# * Snap Docs
#   https://snapdocs.labix.org
# * Latest doc topics in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft

name: utsushi-plugin-gt-s650
summary: Non-free, non-redistributable device support plugin for GT-S650
description: |
  This is the non-free, non-redistributable device support plugin content snap for scanners like Epson Perfection V39.  Due to the restrictions of the SEIKO EPSON CORPORATION SOFTWARE LICENSE AGREEMENT this snap is currently not available on the Snap Store and has to be built by the end user themselves.

  This snap is NOT OFFICIAL, for any issues regarding the use of this snap please refer the issue tracker:
  https://github.com/Lin-Buo-Ren/utsushi-plugin-gt-s650-snap/issues

# Just for humans, typically '1.2+git' or '1.3.2'
# The wrapping single quotes are often required to avoid the version string
# being accidentally interpreted as a YAML non-string(like '1', '1.2').
# http://yaml.org/type
# https://arp242.net/weblog/yaml_probably_not_so_great_after_all.html#surprising-behaviour
version: determined-by-version-script

# (OPTIONAL) The version string can also be dynamically determined via scripting
# , in this case the value of the `version` key will be ignored (but the key is
# still required).
# NOTE: The resulting version string cannot be longer than 32 characters
version-script: ./snap/utilities/set-snap-version.bash
#version-script: git -C parts/my-app-part/src describe --always --dirty --tags

confinement: devmode
grade: devel
icon: snap/gui/icon.png

slots:

parts:
  # Assets from the snap packaging, refer each READMEs under the `snap` folder for more information
  assets:
    plugin: nil

    override-pull: |
      set \
        -o errexit \
        -o nounset

      # Clear all files in source tree
      rm \
        --force \
        --recursive \
        --verbose \
        * \
        .* \
        || true # Allow no files found

      cp \
        --recursive \
        --verbose \
        ../../../snap/* \
        .

    override-build: |
      set \
        -o errexit \
        -o nounset

      ./utilities/install-assets.bash
    prime:
    - -utilities
    - -patches

  imagescan-plugin-gt-s650:
    after:
    - assets # for utilities/patch-desktop-entries

    #source:
    #source-type:
    #source-tag:
    #source-depth:

    plugin: nil

    override-stage: |
      set \
        -o errexit \
        -o nounset

      snapcraftctl stage

      utilities/patch-desktop-entries.bash
